// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SirAntsABot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3244.SirAntsABot.RobotMap;
import org.usfirst.frc3244.SirAntsABot.subsystems.*;

/**
 *
 */
public class Auto_Cycle_Secure_Ball extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public Auto_Cycle_Secure_Ball() {

  
       
        addSequential(new Wrist_To_Stow(RobotMap.WRIST_STOW_ANGLE),3);
        addSequential(new Auto_Ready_Ball());
        addSequential(new Claw_To_Position(13.5),2); //2 seconds to close claw
        addSequential(new Auto_Cycle_Secure_Ball_Complete());


  
 
    } 
}
