// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SirAntsABot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3244.SirAntsABot.Robot;

/**
 *
 */
public class SeaLegs_Jog_FWD extends Command {
	
	 private double m_SeaLeg_Left_Pos;
	 private double m_SeaLeg_Right_Pos;
	 private double m_SeaLeg_Left_delta_to_TDC;
	 private double m_SeaLeg_Right_delta_to_TDC;
	private boolean left_Leg_Not_TDC;
	private boolean right_Leg_Not_TDC;
	 
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public SeaLegs_Jog_FWD() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.seaLegs);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double powerFWD = Robot.oi.xbox_1.getRawAxis(3);
    	double powerREV = -1 * Robot.oi.xbox_1.getRawAxis(2);
    
    	double power = Robot.seaLegs.target(powerFWD + powerREV,.1,-0.85,0.85);
    	
    	if(Math.abs(power)>0){
    		Robot.seaLegs.my_SeaLegs_drive_Tank(power, power);
    	}else{
    		m_SeaLeg_Left_Pos = Robot.seaLegs.my_Get_Left_Encoder();
        	m_SeaLeg_Right_Pos = Robot.seaLegs.my_Get_Right_Encoder();
        	
        	m_SeaLeg_Left_delta_to_TDC = m_SeaLeg_Left_Pos % 360;
        	m_SeaLeg_Right_delta_to_TDC = m_SeaLeg_Right_Pos % 360;

        	double left_kp = 0.2;
        	double right_kp = 0.2;
        	
        	double powerLeft = Robot.seaLegs.target(m_SeaLeg_Left_delta_to_TDC * left_kp, 0, -0.75, 0.75);
        	double powerRight = Robot.seaLegs.target(m_SeaLeg_Right_delta_to_TDC * right_kp, 0, -0.75, 0.75);
        	
        	//force power Off if on switch
        	if(Robot.seaLegs.my_SeaLeg_Left_At_TDC()){
        		powerLeft=0.0;
        	}
        	if(Robot.seaLegs.my_SeaLeg_Right_At_TDC()){
        		powerRight=0.0;
        	}
        	Robot.seaLegs.my_SeaLegs_drive_Tank(-powerLeft, -powerRight);
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
