// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SirAntsABot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3244.SirAntsABot.Robot;

/**
 *
 */
public class Claw_To_Position extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_setpoint;
    private boolean m_setpoint_OverRide;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Claw_To_Position(double setpoint) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_setpoint = setpoint;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.clawsPID);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_setpoint_OverRide=false;
    }
    public  Claw_To_Position() {
    		
           // m_setpoint = SmartDashboard.getNumber("Claw Shot Setpoint",15);
            requires(Robot.clawsPID);
            m_setpoint_OverRide=true;

        }

    // Called just before this Command runs the first time
    protected void initialize() {
    	//OverRide the m_setpoint if called from the no parameter constructor
    	 if (m_setpoint_OverRide){
         	m_setpoint = SmartDashboard.getNumber("Claw Shot Setpoint",15);
         	System.out.println("Claw_To_Position Using SmartDashboard Settings "+ m_setpoint);
         	
         }else{
         	System.out.println("Claw_To_Position Construtor Parameter "+ m_setpoint);
         }
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        Robot.clawsPID.enable();
        Robot.clawsPID.setSetpoint(m_setpoint);
        //Claw has move can not guaranty ball
        Robot.oi.launchPad.setOutput(1, false);
       

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
       
        return Robot.clawsPID.getPosition()<Robot.clawsPID.getSetpoint()+.2 &&
        		Robot.clawsPID.getPosition()>Robot.clawsPID.getSetpoint()-.2;

   
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("Claw_To_Positino_END");
    	Robot.clawsPID.setSetpoint(Robot.clawsPID.getPosition());
    	Robot.clawsPID.disable();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("Claw_To_Positino_INTERRUPTED");
    	end();
    }
}
