// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SirAntsABot.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3244.SirAntsABot.Robot;

/**
 *
 */
public class PinBall_Shoot extends Command {

	Timer t = new Timer();
	double thisScan = 0;
	double shotTime = 2;
	private boolean isAuto;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public PinBall_Shoot() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pinBall);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.isAuto = false;
    }
    public PinBall_Shoot(boolean isAuto) {
      
            requires(Robot.pinBall);
            if(isAuto){
            	this.isAuto = true;
            }else{
            	this.isAuto = false;
            }
        }

    // Called just before this Command runs the first time
    protected void initialize() {
    	t.start();
    	t.reset();   
    	thisScan = t.get();
    	
    	Robot.pinBall.my_initializeCounter();
    	Integer goalChoice = (Integer) Robot.goalChooser.getSelected();
    	if (this.isAuto && goalChoice==0){
    		System.out.println("No Shot");
    		end();
    	}else{
    		Robot.pinBall.myPinballMotorRun();
    	}
    	
    }

  

	// Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	thisScan = t.get();
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	//Wait ? seconds
        return thisScan>shotTime && Robot.pinBall.my_isSwitchSet();
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("Pinball_Shoot_END");
    	Robot.pinBall.myPinballMotorStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("Pinball_Shoot_INTERRUPTED");
    	end();
    }
}
