// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Stronghold_Advanced.subsystems;

import org.usfirst.frc3244.Stronghold_Advanced.RobotMap;
import org.usfirst.frc3244.Stronghold_Advanced.commands.*;

import edu.wpi.first.wpilibj.PowerDistributionPanel;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Control extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final PowerDistributionPanel powerDistributionPanel = RobotMap.controlPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    //Drive Train
    public double my_Get_LeftFront_Current(){
    	return powerDistributionPanel.getCurrent(2);
    }
    public double my_Get_LeftRear_Current(){
    	return powerDistributionPanel.getCurrent(12); //Double up
    }
    public double my_Get_RighFront_Current(){
    	return powerDistributionPanel.getCurrent(1);
    }
    public double my_Get_RightRear_Current(){
    	return powerDistributionPanel.getCurrent(15);
    }
    
    //SeaLegs
    public double my_Get_LeftSeaLeg_Current(){
    	return powerDistributionPanel.getCurrent(12); //Double up
    }
    public double my_Get_RightSeaLeg_Current(){
    	return powerDistributionPanel.getCurrent(14);
    }
    
    //Claw, Wrist, Pinball
    public double my_Get_Claw_Current(){
    	return powerDistributionPanel.getCurrent(11);
    }
    public double my_Get_Pinball_Current(){
    	return powerDistributionPanel.getCurrent(10);
    }
    public double my_Get_Wrist_Current(){
    	return powerDistributionPanel.getCurrent(7);
    }
    
    //Scissor
    public double my_Get_Scissor_Current(){
    	return powerDistributionPanel.getCurrent(3);
    }
    
    
    //System Information
    public double my_Get_Total_Current(){
    	return powerDistributionPanel.getTotalCurrent();
    }
    public double my_Get_Voltage_Current(){
    	return powerDistributionPanel.getVoltage();
    }
    
    public void updateStatus(){
    	
    }
}

