// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Stronghold_Advanced.subsystems;

import org.usfirst.frc3244.Stronghold_Advanced.RobotMap;
import org.usfirst.frc3244.Stronghold_Advanced.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class SeaLegs extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon motor_Left_CAN = RobotMap.seaLegsMotor_Left_CAN;
    private final CANTalon motor_Right_CAN = RobotMap.seaLegsMotor_Right_CAN;
    private final Encoder encoder_Left = RobotMap.seaLegsEncoder_Left;
    private final Encoder encoder_Right = RobotMap.seaLegsEncoder_Right;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private final NordicSpeedController nordic_Left = RobotMap.nordic_SeaLegsLeft;
    private final NordicSpeedController nordic_Right = RobotMap.nordic_SeaLegsRight;
    
    private final RobotDrive robotDrive_SeaLegs = RobotMap.seaLegsRobotDrive;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void my_Walk_Sealegs_Timed(double leftValue,double rightValue){
    	robotDrive_SeaLegs.tankDrive(leftValue, rightValue);;
    }
    
    public void my_Jog_Left_SeaLeg(double speed){
    	nordic_Left.set(speed);
    }
    public void my_Jog_Right_SeaLeg(double speed){
    	nordic_Left.set(speed);
    }
    
    //Encoders
    public void my_LeftEncoder_Reset(){
    	encoder_Left.reset();
    }
    public void my_RightEncoder_Reset(){
    	encoder_Left.reset();
    }
    
    
    public double my_GetLeftEncoder(){
    	return encoder_Left.get();
    }
    public double my_GetRightEncoder(){
    	return encoder_Left.get();
    }
    public void updateStatus(){
    	
    }
}

