// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.CMBA.commands;
import org.usfirst.frc3244.CMBA.RobotMap;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class CG_Finally extends CommandGroup {
    
    public  CG_Finally() {
    	addSequential(new LiftToTop());
    	addSequential(new DriveSpinInPlace(180));
    	addParallel(new LiftToBottom());
    	addSequential(new DriveSpinInPlace(-160));
    }
}
