// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.CMBA.commands;

import java.util.LinkedList;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3244.CMBA.Robot;

/**
 *
 */
public class  DriveToSetToteOnOne extends Command {
	
	private static final double toteSetOnOnePosition = .18;
	private static LinkedList<Double> fifo = null;
	private static double averagegyro = 0;
	private static boolean sample_gyro = false;
	private static double target_gyro = 0;
	 private static double travle = 0;

    public DriveToSetToteOnOne() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	sample_gyro = false;
    	fifo = new LinkedList<Double>();
    	fifo.clear();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(fifo.size()>9){
    		double sum = 0;
    		for(int i =0;i<fifo.size();i++){
    			sum = sum + fifo.get(i);
    		}
    		averagegyro = sum/fifo.size();
    		fifo.removeFirst();
    		
    		if(!sample_gyro){
    			travle = Robot.driveSystem.getUSDistance() - toteSetOnOnePosition;
        		target_gyro = averagegyro;
        		sample_gyro = true;
        	}
    		double kp = SmartDashboard.getNumber("Drive Straight Correction");
    		double correction = (target_gyro - averagegyro)*kp;
    		double kpSpeed=(Robot.driveSystem.getUSDistance() - toteSetOnOnePosition)/travle;
    		double commandSpeed = SmartDashboard.getNumber("Dive to Tote Speed")*kpSpeed;
    		if (commandSpeed<.35)commandSpeed=.35;
    		SmartDashboard.putNumber("kpSpeed", kpSpeed);
    		Robot.driveSystem.driveStraight(commandSpeed,correction);
    	}
    	fifo.add(new Double(Robot.driveSystem.getGyro()));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.driveSystem.getUSDistance() < toteSetOnOnePosition;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveSystem.driveStraight(0,0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
