// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3018.Iajax.commands;
import org.usfirst.frc3018.Iajax.subsystems.Lifter;
import org.usfirst.frc3018.Iajax.subsystems.Pincher;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AdvanceCratesOnGround extends CommandGroup {
    
    public  AdvanceCratesOnGround() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	addSequential(new MoveForks(Lifter.LiftPosition.RELEASE_ON_TOTE_ON_GROUND));
    	addSequential(new MovePincherToSetpoint(Pincher.PinchPosition.AVOID_TOP_POSITION,true));
    	addSequential(new MoveForks(Lifter.LiftPosition.TOTE_TOP_ON_GROUND));
    	addParallel(new MovePincherToSetpoint(Pincher.PinchPosition.LIFT_TOTE_POSITION));
    	addSequential(new MoveForks(Lifter.LiftPosition.LIFT_FROM_GROUND));
    	addSequential(new MoveForks(Lifter.LiftPosition.CARRY_FOR_STACK_WHILE_DRIVING));
    }
}