// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3018.Iajax.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3018.Iajax.Robot;

/**
 *
 */
public class  ControllLifterWithJoysticks extends Command {
	private MoveLifterToSetPoint m_lifterCommand;

    public ControllLifterWithJoysticks() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
  	 	m_lifterCommand = new MoveLifterToSetPoint(0.0);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lifter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Math.abs(Robot.oi.getLeftJoystick().getY()) > 0.25  ) {
    		Robot.lifter.raiseLifter(-Robot.oi.getLeftJoystick().getY());
    		//Robot.lifter.raiseLifter(-Robot.oi.getRightJoystick().getRawAxis(6));
    	} else if(Robot.lifter.getHeight()>30) {
    		m_lifterCommand.setNewSetpoint(Robot.lifter.getHeight());
    		m_lifterCommand.start();  
    	} else {
    		Robot.lifter.raiseLifterManual(0);
    	}
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
