// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3018.Iajax.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3018.Iajax.Robot;
import org.usfirst.frc3018.Iajax.subsystems.Pincher;

/**
 *
 */
public class  MovePincherToSetpoint extends Command {

	double m_setpoint;
	boolean m_returnOnTarget;
	
    public MovePincherToSetpoint(double setpoint, boolean returnOnTarget) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pincher);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_setpoint = setpoint;
        m_returnOnTarget = returnOnTarget;
    }

    public MovePincherToSetpoint(Pincher.PinchPosition pos) {
    	this(pos,false);
    }
    
    public MovePincherToSetpoint() {
    	this(Pincher.PinchPosition.WIDE_OPEN_POSITION);
    }
    
    public MovePincherToSetpoint(Pincher.PinchPosition pos, boolean returnOnTarget) {
    	this(pos.getSetpoint(), returnOnTarget);
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.pincher.setSetpoint(m_setpoint);
    	Robot.pincher.enable();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (m_returnOnTarget) {
    		return Robot.pincher.onTarget();
    	}
        return Math.abs(Robot.oi.getRightJoystick().getX())>0.25;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
