// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3018.Iajax.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3018.Iajax.Robot;
import org.usfirst.frc3018.Iajax.subsystems.Lifter;

/**
 *
 */
public class  MoveForks extends Command {

	double m_setpoint;
	
    public MoveForks(double setpoint) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	m_setpoint = setpoint;
    }
    
    public MoveForks() {
    	this(0.0);   	
    }
    
    public MoveForks(Lifter.LiftPosition pos) {
    	this(pos.getSetpoint());
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	MoveLifterToSetPoint newCommand = new MoveLifterToSetPoint(m_setpoint);
    	newCommand.start();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Math.abs(Robot.lifter.getHeight() - m_setpoint) < 5.0;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
