// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3018.Iajax.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3018.Iajax.Robot;

/**
 *
 */
public class  resetLiftPID extends Command {

    private double m_setpoint;

	public resetLiftPID() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lifter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(1.0);
    	double pvalue = SmartDashboard.getNumber("lift P");
    	double ivalue = SmartDashboard.getNumber("lift I");
    	double dvalue = SmartDashboard.getNumber("lift D");
    	m_setpoint =SmartDashboard.getNumber("Lift Setpoint");
    	
    	Robot.lifter.resetPID(pvalue, ivalue, dvalue, 0);
    	SmartDashboard.putBoolean("lift enabled", true);
    	System.out.println("Pvalue="+pvalue+" IValue="+ivalue+" DValue="+dvalue+" Setpoint="+m_setpoint);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.lifter.raiseLifter(m_setpoint);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lifter.disablePIDs();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.lifter.disablePIDs();
    }
}
