// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.Stronghold.subsystems;

import org.usfirst.frc3244.Stronghold.RobotMap;
import org.usfirst.frc3244.Stronghold.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController front_Left = RobotMap.driveTrainFront_Left;
    private final SpeedController front_Right = RobotMap.driveTrainFront_Right;
    private final SpeedController rear_Left = RobotMap.driveTrainRear_Left;
    private final SpeedController rear_Right = RobotMap.driveTrainRear_Right;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    private final Encoder front_Left_Encoder = RobotMap.driveTrainFront_Left_Encoder;
    private final Encoder front_Right_Encoder = RobotMap.driveTrainFront_Right_Encoder;
    private final Encoder rear_Left_Encoder = RobotMap.driveTrainRear_Left_Encoder;
    private final Encoder rear_Right_Encoder = RobotMap.driveTrainRear_Right_Encoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new MecanumDrive());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void Mecanum_Drive(double x, double y, double rotation, double gyroAngle) {
    	robotDrive.mecanumDrive_Cartesian(x, y, rotation, gyroAngle);
    }
    
}

